//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRestLibrary.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8001/dp2library/rest/")]
        public string global_url {
            get {
                return ((string)(this["global_url"]));
            }
            set {
                this["global_url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string login_userName {
            get {
                return ((string)(this["login_userName"]));
            }
            set {
                this["login_userName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string login_password {
            get {
                return ((string)(this["login_password"]));
            }
            set {
                this["login_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string writeRes_respath {
            get {
                return ((string)(this["writeRes_respath"]));
            }
            set {
                this["writeRes_respath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getReaderInfo_barcode {
            get {
                return ((string)(this["getReaderInfo_barcode"]));
            }
            set {
                this["getReaderInfo_barcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getReaderInfo_resultTypeList {
            get {
                return ((string)(this["getReaderInfo_resultTypeList"]));
            }
            set {
                this["getReaderInfo_resultTypeList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setReaderInfo_action {
            get {
                return ((string)(this["setReaderInfo_action"]));
            }
            set {
                this["setReaderInfo_action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setReaderInfo_resPath {
            get {
                return ((string)(this["setReaderInfo_resPath"]));
            }
            set {
                this["setReaderInfo_resPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setReaderInfo_newXml {
            get {
                return ((string)(this["setReaderInfo_newXml"]));
            }
            set {
                this["setReaderInfo_newXml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setReaderInfo_oldXml {
            get {
                return ((string)(this["setReaderInfo_oldXml"]));
            }
            set {
                this["setReaderInfo_oldXml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setReaderInfo_oldTimestamp {
            get {
                return ((string)(this["setReaderInfo_oldTimestamp"]));
            }
            set {
                this["setReaderInfo_oldTimestamp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string login_parameters {
            get {
                return ((string)(this["login_parameters"]));
            }
            set {
                this["login_parameters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setLang_lang {
            get {
                return ((string)(this["setLang_lang"]));
            }
            set {
                this["setLang_lang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string verifyReaderPassword_readerBarcode {
            get {
                return ((string)(this["verifyReaderPassword_readerBarcode"]));
            }
            set {
                this["verifyReaderPassword_readerBarcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string verifyReaderPassword_password {
            get {
                return ((string)(this["verifyReaderPassword_password"]));
            }
            set {
                this["verifyReaderPassword_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string changeReaderPassword_readerBarcode {
            get {
                return ((string)(this["changeReaderPassword_readerBarcode"]));
            }
            set {
                this["changeReaderPassword_readerBarcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string changeReaderPassword_password_old {
            get {
                return ((string)(this["changeReaderPassword_password_old"]));
            }
            set {
                this["changeReaderPassword_password_old"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string changeReaderPassword_password_new {
            get {
                return ((string)(this["changeReaderPassword_password_new"]));
            }
            set {
                this["changeReaderPassword_password_new"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string writeRes_ranges {
            get {
                return ((string)(this["writeRes_ranges"]));
            }
            set {
                this["writeRes_ranges"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string writeRes_totalLength {
            get {
                return ((string)(this["writeRes_totalLength"]));
            }
            set {
                this["writeRes_totalLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string writeRes_content {
            get {
                return ((string)(this["writeRes_content"]));
            }
            set {
                this["writeRes_content"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string writeRes_metadata {
            get {
                return ((string)(this["writeRes_metadata"]));
            }
            set {
                this["writeRes_metadata"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string writeRes_style {
            get {
                return ((string)(this["writeRes_style"]));
            }
            set {
                this["writeRes_style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string writeRes_inputTimestamp {
            get {
                return ((string)(this["writeRes_inputTimestamp"]));
            }
            set {
                this["writeRes_inputTimestamp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string searchBiblio_queryWord {
            get {
                return ((string)(this["searchBiblio_queryWord"]));
            }
            set {
                this["searchBiblio_queryWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string searchBiblio_fromStyle {
            get {
                return ((string)(this["searchBiblio_fromStyle"]));
            }
            set {
                this["searchBiblio_fromStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string searchBiblio_biblioDbNames {
            get {
                return ((string)(this["searchBiblio_biblioDbNames"]));
            }
            set {
                this["searchBiblio_biblioDbNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string searchBiblio_resultSetName {
            get {
                return ((string)(this["searchBiblio_resultSetName"]));
            }
            set {
                this["searchBiblio_resultSetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string searchBiblio_matchStyle {
            get {
                return ((string)(this["searchBiblio_matchStyle"]));
            }
            set {
                this["searchBiblio_matchStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string searchBiblio_perMax {
            get {
                return ((string)(this["searchBiblio_perMax"]));
            }
            set {
                this["searchBiblio_perMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string searchBiblio_lang {
            get {
                return ((string)(this["searchBiblio_lang"]));
            }
            set {
                this["searchBiblio_lang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string searchBiblio_searchStyle {
            get {
                return ((string)(this["searchBiblio_searchStyle"]));
            }
            set {
                this["searchBiblio_searchStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string searchBiblio_outputStyle {
            get {
                return ((string)(this["searchBiblio_outputStyle"]));
            }
            set {
                this["searchBiblio_outputStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getSearchResult_resultsetName {
            get {
                return ((string)(this["getSearchResult_resultsetName"]));
            }
            set {
                this["getSearchResult_resultsetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getSearchResult_start {
            get {
                return ((string)(this["getSearchResult_start"]));
            }
            set {
                this["getSearchResult_start"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getSearchResult_count {
            get {
                return ((string)(this["getSearchResult_count"]));
            }
            set {
                this["getSearchResult_count"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getSearchResult_browseInfoStyle {
            get {
                return ((string)(this["getSearchResult_browseInfoStyle"]));
            }
            set {
                this["getSearchResult_browseInfoStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getSearchResult_lang {
            get {
                return ((string)(this["getSearchResult_lang"]));
            }
            set {
                this["getSearchResult_lang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string searchReader_queryWord {
            get {
                return ((string)(this["searchReader_queryWord"]));
            }
            set {
                this["searchReader_queryWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string searchReader_from {
            get {
                return ((string)(this["searchReader_from"]));
            }
            set {
                this["searchReader_from"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string searchReader_readerDbNames {
            get {
                return ((string)(this["searchReader_readerDbNames"]));
            }
            set {
                this["searchReader_readerDbNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string searchReader_resultSetName {
            get {
                return ((string)(this["searchReader_resultSetName"]));
            }
            set {
                this["searchReader_resultSetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string searchReader_matchStyle {
            get {
                return ((string)(this["searchReader_matchStyle"]));
            }
            set {
                this["searchReader_matchStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string searchReader_perMax {
            get {
                return ((string)(this["searchReader_perMax"]));
            }
            set {
                this["searchReader_perMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string searchReader_lang {
            get {
                return ((string)(this["searchReader_lang"]));
            }
            set {
                this["searchReader_lang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string searchReader_outputStyle {
            get {
                return ((string)(this["searchReader_outputStyle"]));
            }
            set {
                this["searchReader_outputStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getBiblioInfo_biblioRecPath {
            get {
                return ((string)(this["getBiblioInfo_biblioRecPath"]));
            }
            set {
                this["getBiblioInfo_biblioRecPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getBiblioInfo_biblioType {
            get {
                return ((string)(this["getBiblioInfo_biblioType"]));
            }
            set {
                this["getBiblioInfo_biblioType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getItemInfo_barcode {
            get {
                return ((string)(this["getItemInfo_barcode"]));
            }
            set {
                this["getItemInfo_barcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getItemInfo_resultType {
            get {
                return ((string)(this["getItemInfo_resultType"]));
            }
            set {
                this["getItemInfo_resultType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getItemInfo_biblioType {
            get {
                return ((string)(this["getItemInfo_biblioType"]));
            }
            set {
                this["getItemInfo_biblioType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getEntities_biblioRecPath {
            get {
                return ((string)(this["getEntities_biblioRecPath"]));
            }
            set {
                this["getEntities_biblioRecPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getEntities_start {
            get {
                return ((string)(this["getEntities_start"]));
            }
            set {
                this["getEntities_start"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getEntities_count {
            get {
                return ((string)(this["getEntities_count"]));
            }
            set {
                this["getEntities_count"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getEntities_style {
            get {
                return ((string)(this["getEntities_style"]));
            }
            set {
                this["getEntities_style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getEntities_lang {
            get {
                return ((string)(this["getEntities_lang"]));
            }
            set {
                this["getEntities_lang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getBiblioSummary_itemBarcode {
            get {
                return ((string)(this["getBiblioSummary_itemBarcode"]));
            }
            set {
                this["getBiblioSummary_itemBarcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getBiblioSummary_confirmItemRecPath {
            get {
                return ((string)(this["getBiblioSummary_confirmItemRecPath"]));
            }
            set {
                this["getBiblioSummary_confirmItemRecPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getBiblioSummary_biblioRecPathExclude {
            get {
                return ((string)(this["getBiblioSummary_biblioRecPathExclude"]));
            }
            set {
                this["getBiblioSummary_biblioRecPathExclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getOperLog_fileName {
            get {
                return ((string)(this["getOperLog_fileName"]));
            }
            set {
                this["getOperLog_fileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getOperLog_index {
            get {
                return ((string)(this["getOperLog_index"]));
            }
            set {
                this["getOperLog_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getOperLog_hint {
            get {
                return ((string)(this["getOperLog_hint"]));
            }
            set {
                this["getOperLog_hint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getOperLog_attachmentFragmentStart {
            get {
                return ((string)(this["getOperLog_attachmentFragmentStart"]));
            }
            set {
                this["getOperLog_attachmentFragmentStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getOperLog_attachmentFragmentLength {
            get {
                return ((string)(this["getOperLog_attachmentFragmentLength"]));
            }
            set {
                this["getOperLog_attachmentFragmentLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getBrowseRecords_paths {
            get {
                return ((string)(this["getBrowseRecords_paths"]));
            }
            set {
                this["getBrowseRecords_paths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getBrowseRecords_browseInfoStyle {
            get {
                return ((string)(this["getBrowseRecords_browseInfoStyle"]));
            }
            set {
                this["getBrowseRecords_browseInfoStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string return_action {
            get {
                return ((string)(this["return_action"]));
            }
            set {
                this["return_action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string return_readerBarcode {
            get {
                return ((string)(this["return_readerBarcode"]));
            }
            set {
                this["return_readerBarcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string return_itemBarcode {
            get {
                return ((string)(this["return_itemBarcode"]));
            }
            set {
                this["return_itemBarcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string return_comfirmItemRecPath {
            get {
                return ((string)(this["return_comfirmItemRecPath"]));
            }
            set {
                this["return_comfirmItemRecPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string return_style {
            get {
                return ((string)(this["return_style"]));
            }
            set {
                this["return_style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string return_itemFormatList {
            get {
                return ((string)(this["return_itemFormatList"]));
            }
            set {
                this["return_itemFormatList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string return_readerFormatList {
            get {
                return ((string)(this["return_readerFormatList"]));
            }
            set {
                this["return_readerFormatList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string return_biblioFormatList {
            get {
                return ((string)(this["return_biblioFormatList"]));
            }
            set {
                this["return_biblioFormatList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string passGate_readerBarcode {
            get {
                return ((string)(this["passGate_readerBarcode"]));
            }
            set {
                this["passGate_readerBarcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string passGate_gateName {
            get {
                return ((string)(this["passGate_gateName"]));
            }
            set {
                this["passGate_gateName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string passGate_resultTypeList {
            get {
                return ((string)(this["passGate_resultTypeList"]));
            }
            set {
                this["passGate_resultTypeList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getStatisInfo_dateRangeString {
            get {
                return ((string)(this["getStatisInfo_dateRangeString"]));
            }
            set {
                this["getStatisInfo_dateRangeString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getAuthorNumber_strAuthor {
            get {
                return ((string)(this["getAuthorNumber_strAuthor"]));
            }
            set {
                this["getAuthorNumber_strAuthor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool getAuthorNumber_bSelectPinyin {
            get {
                return ((bool)(this["getAuthorNumber_bSelectPinyin"]));
            }
            set {
                this["getAuthorNumber_bSelectPinyin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool getAuthorNumber_bSelectEntry {
            get {
                return ((bool)(this["getAuthorNumber_bSelectEntry"]));
            }
            set {
                this["getAuthorNumber_bSelectEntry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool getAuthorNumber_bOutputDebugInfo {
            get {
                return ((bool)(this["getAuthorNumber_bOutputDebugInfo"]));
            }
            set {
                this["getAuthorNumber_bOutputDebugInfo"] = value;
            }
        }
    }
}
